on:
  push:
    branches:
      - main
  pull_request:

name: Unit Tests

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"

      - name: Set environment variable from secret
        run: echo "export MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: make install

      - name: Build Contracts
      env: 
    WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        run: make build

      - name: Run Tests
        run: make test

      - name: Run Benchmarks
        run: |
          make bench
          make snapshot
